# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: mvnizer 0.10.0 ruby lib

Gem::Specification.new do |s|
  s.name = "mvnizer".freeze
  s.version = "0.10.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["S\u{e9}bastien Le Callonnec".freeze]
  s.date = "2020-10-21"
  s.description = "Bootstrap a Maven project without the pain of archetypes.".freeze
  s.email = "sebastien@weblogism.com".freeze
  s.executables = ["mvnizer".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.org"
  ]
  s.files = [
    ".rspec",
    ".travis.yml",
    "CHANGELOG.org",
    "Dockerfile",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.org",
    "Rakefile",
    "TODO.org",
    "bin/mvnizer",
    "conf/default.yml",
    "features/new_project.feature",
    "features/search_artefact.feature",
    "features/step_definitions/pom_steps.rb",
    "features/support/env.rb",
    "lib/mvnizer.rb",
    "lib/mvnizer/commands.rb",
    "lib/mvnizer/commands/add_dependency.rb",
    "lib/mvnizer/commands/new_project.rb",
    "lib/mvnizer/commands/new_war_project.rb",
    "lib/mvnizer/commands/project_factory.rb",
    "lib/mvnizer/commands/search_artefact.rb",
    "lib/mvnizer/configuration.rb",
    "lib/mvnizer/coordinate_parser.rb",
    "lib/mvnizer/erb_helper.rb",
    "lib/mvnizer/exceptions.rb",
    "lib/mvnizer/mvnize.rb",
    "lib/mvnizer/plugin.rb",
    "lib/mvnizer/project.rb",
    "lib/mvnizer/task_helper.rb",
    "lib/mvnizer/templates/_dependency.xml.erb",
    "lib/mvnizer/templates/_plugin.xml.erb",
    "lib/mvnizer/templates/editorconfig.erb",
    "lib/mvnizer/templates/gitignore.erb",
    "lib/mvnizer/templates/pom.xml.erb",
    "lib/mvnizer/templates/war/ExampleServlet.java.erb",
    "lib/mvnizer/templates/war/index.jsp.erb",
    "lib/mvnizer/templates/web.xml.erb",
    "lib/mvnizer/version.rb",
    "mvnizer.gemspec",
    "ragel/coordinate.rb",
    "ragel/coordinate.rl",
    "ragel/test_coord.rb",
    "spec/commands/add_dependency_spec.rb",
    "spec/commands/new_project_spec.rb",
    "spec/commands/new_war_project_spec.rb",
    "spec/commands/project_factory_spec.rb",
    "spec/commands/search_artefact_spec.rb",
    "spec/configuration_spec.rb",
    "spec/coordinate_parser_spec.rb",
    "spec/dummy.txt.erb",
    "spec/dummy_pom.xml",
    "spec/mvnize_spec.rb",
    "spec/project_spec.rb",
    "spec/spec_helper.rb",
    "spec/task_helper_spec.rb"
  ]
  s.homepage = "http://github.com/tychobrailleur/mvnizer".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.7.8".freeze
  s.summary = "Bootstrap a Maven project without the pain of archetypes.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>.freeze, ["~> 0.16"])
      s.add_runtime_dependency(%q<nokogiri>.freeze, ["~> 1.10"])
      s.add_runtime_dependency(%q<rake>.freeze, ["< 11.0"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 2.99"])
      s.add_development_dependency(%q<rspec-mocks>.freeze, ["~> 2.99"])
      s.add_development_dependency(%q<fakefs>.freeze, ["~> 0.14"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3"])
      s.add_development_dependency(%q<aruba>.freeze, ["~> 0.14"])
    else
      s.add_dependency(%q<httparty>.freeze, ["~> 0.16"])
      s.add_dependency(%q<nokogiri>.freeze, ["~> 1.10"])
      s.add_dependency(%q<rake>.freeze, ["< 11.0"])
      s.add_dependency(%q<rspec>.freeze, ["~> 2.99"])
      s.add_dependency(%q<rspec-mocks>.freeze, ["~> 2.99"])
      s.add_dependency(%q<fakefs>.freeze, ["~> 0.14"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3"])
      s.add_dependency(%q<aruba>.freeze, ["~> 0.14"])
    end
  else
    s.add_dependency(%q<httparty>.freeze, ["~> 0.16"])
    s.add_dependency(%q<nokogiri>.freeze, ["~> 1.10"])
    s.add_dependency(%q<rake>.freeze, ["< 11.0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 2.99"])
    s.add_dependency(%q<rspec-mocks>.freeze, ["~> 2.99"])
    s.add_dependency(%q<fakefs>.freeze, ["~> 0.14"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3"])
    s.add_dependency(%q<aruba>.freeze, ["~> 0.14"])
  end
end

