# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mvnizer"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["S\u{e9}bastien Le Callonnec"]
  s.date = "2012-09-17"
  s.description = "Bootstrap a Maven project without the pain of archetypes."
  s.email = "sebastien@weblogism.com"
  s.executables = ["mvnizer"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "TODO.md",
    "bin/mvnizer",
    "conf/default.yml",
    "lib/mvnizer.rb",
    "lib/mvnizer/configuration.rb",
    "lib/mvnizer/coordinate_parser.rb",
    "lib/mvnizer/dir_creator.rb",
    "lib/mvnizer/erb_helper.rb",
    "lib/mvnizer/mvnize.rb",
    "lib/mvnizer/pom_generator.rb",
    "lib/mvnizer/project.rb",
    "lib/mvnizer/templates/_dependency.xml.erb",
    "lib/mvnizer/templates/pom.xml.erb",
    "lib/mvnizer/version.rb",
    "mvnizer.gemspec",
    "ragel/coordinate.rb",
    "ragel/coordinate.rl",
    "ragel/test_coord.rb",
    "spec/configuration_spec.rb",
    "spec/coordinate_parser_spec.rb",
    "spec/dir_creator_spec.rb",
    "spec/generator_spec.rb",
    "spec/mvnize_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/tychobrailleur/mvnizer"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Bootstrap a Maven project without the pain of archetypes."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.11.0"])
      s.add_development_dependency(%q<rspec-mocks>, ["~> 2.11.2"])
      s.add_development_dependency(%q<fakefs>, ["~> 0.4.0"])
      s.add_development_dependency(%q<nokogiri>, ["~> 1.5.5"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.11.0"])
      s.add_dependency(%q<rspec-mocks>, ["~> 2.11.2"])
      s.add_dependency(%q<fakefs>, ["~> 0.4.0"])
      s.add_dependency(%q<nokogiri>, ["~> 1.5.5"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.11.0"])
    s.add_dependency(%q<rspec-mocks>, ["~> 2.11.2"])
    s.add_dependency(%q<fakefs>, ["~> 0.4.0"])
    s.add_dependency(%q<nokogiri>, ["~> 1.5.5"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

