group_id: com.example
version: 0.0.1-SNAPSHOT
type: jar
dependencies: [ "org.junit.jupiter:junit-jupiter-engine:5.8.2:jar:test" ]
plugins: [ ":maven-compiler-plugin:3.10.0" ]
logging_deps: [ "org.slf4j:slf4j-api:1.7.36:jar",
                "org.slf4j:slf4j-simple:1.7.36:jar",
                "ch.qos.logback:logback-core:1.2.11:jar" ]
